# Generated by Django 4.1.5 on 2023-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de admin')),
                ('rut', models.IntegerField(verbose_name='rut del admin')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre del admin')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido del admin')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion del admin')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de empleado')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre empleado')),
                ('apellidos', models.CharField(max_length=30, verbose_name='apellido empleado')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion empleado')),
            ],
        ),
        migrations.CreateModel(
            name='happyfootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre de la empresa')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripción de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion del producto')),
                ('peso', models.IntegerField(verbose_name='peso del producto')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('fotoProd', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='registro_venta',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de pedido')),
                ('cantidad', models.IntegerField(verbose_name='cantidad de producto')),
                ('precio', models.IntegerField(verbose_name='precio de producto')),
                ('fecha', models.DateField(verbose_name='fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='seguridad',
            fields=[
                ('clave', models.CharField(max_length=12, verbose_name='clave de usuario')),
                ('correo', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='correo del usuario')),
                ('correo_respaldo', models.CharField(max_length=30, verbose_name='correo de respaldo del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de usuario')),
                ('rut', models.IntegerField(verbose_name='rut del usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre del usuario')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido del usuario')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion del usuario')),
                ('tarjetas', models.CharField(max_length=50, verbose_name='tarjetas del usuario')),
            ],
        ),
    ]
